### ISSUE TITLE
Support multiple pattern for a file

### ISSUE THREAD

**Issue by kt3k** [kt3k/ruby-bmp#1]
support multiple pattern like below:

```

---
version: 0.1.6
files:
  gradle.properties: version=#{V}
  README.md:
    - coveralls-gradle-plugin v#{V}
    - org.kt3k.gradle.plugin:coveralls-gradle-plugin:#{V}
```
